"use client";
import { useEffect, useState } from 'react';
import { BookOpen, GraduationCap, ArrowRight, LockKeyhole, Check, LogOut, Settings, Sparkles, History, Menu, X } from 'lucide-react';
import type { User } from '@/lib/auth';
import { api, xp } from './api';
import Lesson from './lesson';
import Teacher from './teacher';
export default function Platform({initialUser,configured}:{initialUser:User|null;configured:boolean}){
 const [user,setUser]=useState(initialUser);const [course,setCourse]=useState<any>(null);const [view,setView]=useState('trail');const [lessonId,setLessonId]=useState<string|null>(null);const [notice,setNotice]=useState('');const [mobile,setMobile]=useState(false);
 async function refresh(){try{const [me,data]=await Promise.all([api('me'),api('course')]);setUser(me.user);setCourse(data)}catch(e){setNotice((e as Error).message)}}
 useEffect(()=>{if(user)void refresh()},[user?.id]);
 useEffect(()=>{document.body.classList.toggle('reduce-motion',!!user?.reduce_motion)},[user?.reduce_motion]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),6500);return()=>clearTimeout(timer)},[notice]);
 function openLesson(id:string){setLessonId(id);setView('lesson');setMobile(false);window.scrollTo(0,0)}
 function navigate(next:string){setView(next);setMobile(false);window.scrollTo(0,0)}
 if(!user)return <Login configured={configured} onLogin={async()=>{const data=await api('me');setUser(data.user)}}/>;
 const completed=course?.lessons.filter((l:any)=>l.completed).length||0;const available=course?.lessons.filter((l:any)=>l.published&&(l.released||user.role==='teacher'))||[];const recent=available.filter((l:any)=>!l.completed&&l.updated_at).sort((a:any,b:any)=>new Date(b.updated_at).getTime()-new Date(a.updated_at).getTime());const next=recent[0]||available.find((l:any)=>!l.completed)||available[0];
 return <div className="app-shell"><a href="#content" className="skip">Pular para conteúdo</a><aside className={'sidebar '+(mobile?'visible':'')}><a className="brand" href="/" aria-label="PythonBlock início"><span className="brand-symbol">⌘</span><span>PythonBlock<small>APRENDA PYTHON NA PRÁTICA</small></span></a><div className="sidebar-label">SEU ESPAÇO</div><nav aria-label="Navegação principal"><button className={view==='trail'||view==='lesson'?'active':''} onClick={()=>navigate('trail')}><BookOpen size={19}/> Minha trilha</button>{user.role==='teacher'&&<button className={view==='teacher'?'active':''} onClick={()=>navigate('teacher')}><GraduationCap size={20}/> Painel do professor</button>}<button className={view==='history'?'active':''} onClick={()=>navigate('history')}><History size={19}/> Meu progresso</button><button className={view==='settings'?'active':''} onClick={()=>navigate('settings')}><Settings size={19}/> Minha conta</button></nav><div className="sidebar-bottom"><div className="pet-mark">🐍 <span>Um passo de cada vez.</span></div><p>Aprenda, experimente e volte sempre que precisar.</p><span className="tiny">INTRODUÇÃO AO PYTHON · SENAI</span></div></aside><div className="main-shell"><header className="topbar"><div className="row"><button className="icon-button mobile-toggle" onClick={()=>setMobile(!mobile)} aria-label="Abrir menu">{mobile?<X size={20}/>:<Menu size={20}/>}</button><span className="breadcrumb">Sua jornada <span>/</span> {view==='teacher'?'Professor':view==='lesson'?'Sala de aula':'Python'}</span></div><div className="row"><span className="points"><Sparkles size={15}/> {xp(user.score)} XP</span><span className="profile-avatar" aria-hidden="true">{user.avatar}</span><div className="user-name"><strong>{user.name}</strong><small>{user.role==='teacher'?'Professor':'Aluno'}</small></div><button className="icon-button" title="Sair da conta" aria-label="Sair da conta" onClick={async()=>{try{await api('auth/logout',{});location.assign('/')}catch(e){setNotice((e as Error).message)}}}><LogOut size={18}/></button></div></header><main id="content" tabIndex={-1}>
 {view==='trail'&&<><div className="page-heading"><div><p className="eyebrow">SUA JORNADA EM PYTHON</p><h1>Olá, {user.name.split(' ')[0]}. Vamos aprender?</h1><p className="muted">Pequenas descobertas constroem grandes ideias. Continue no seu ritmo.</p></div><span className="pill">{course?.className||'Carregando turma…'}</span></div><div className="welcome-panel"><div><span className="eyebrow">APRENDA PYTHON</span><h2>Seu próximo passo<br/>começa aqui.</h2><p>Transforme suas ideias em programas Python.<br className="desktop-only"/> Você tem uma equipe para acompanhar cada descoberta.</p>{next?<button className="primary" onClick={()=>openLesson(next.id)}>Continuar minha aula <ArrowRight size={17}/></button>:<p>Seu professor vai liberar a primeira aula em breve.</p>}</div><div className="welcome-art" role="img" aria-label="Símbolos de programação e prática em Python"><div className="orbit"/><span className="art-bubble">Vamos juntos?</span><span className="mascots">🐍 💻</span><span className="art-caption">EXPLORE · PRATIQUE · APRENDA</span></div></div><div className="journey-row"><h2>Seu mapa de aprendizagem</h2><span className="muted">{completed} aulas concluídas</span></div>{!course?<p role="status">Carregando sua trilha…</p>:<div className="chapter-grid">{course.chapters.map((chapter:any)=>{const items=course.lessons.filter((l:any)=>l.chapter===chapter.id);const unlocked=items.filter((l:any)=>l.published&&(l.released||user.role==='teacher'));const done=items.filter((l:any)=>l.completed).length;return <article className={'chapter-card '+(!unlocked.length?'locked':'')} key={chapter.id}><div className="row between"><span className="chapter-icon">{chapter.icon}</span><span className="tiny">CAPÍTULO {String(chapter.id).padStart(2,'0')}</span></div><h3>{chapter.title}</h3><p>{chapter.summary}</p><div className="progress-track" aria-label={`${done} de ${items.length} aulas concluídas`}><span style={{width:(done/items.length*100)+'%'}}/></div><div className="chapter-meta"><span>{done}/{items.length} aulas</span><span>{unlocked.length?'Disponível':'Em breve'}</span></div><details><summary>{unlocked.length?'Ver aulas':'Conhecer os próximos passos'} <ArrowRight size={15}/></summary><ul className="lesson-list">{items.map((l:any)=><li key={l.id}><button disabled={!l.published||(!l.released&&user.role!=='teacher')} onClick={()=>openLesson(l.id)}>{l.completed?<Check size={15}/>:(!l.published||(!l.released&&user.role!=='teacher'))?<LockKeyhole size={14}/>:<span className="lesson-dot"/>}<span>{l.title}<small>{!l.published?'Em preparação':!l.released&&user.role!=='teacher'?'Aguardando liberação':''}</small></span></button></li>)}</ul></details></article>})}</div>}<div className="quiet-note">🌱 Sem pressa e sem comparação. Seu progresso é seu.</div></>}
 {view==='lesson'&&lessonId&&<Lesson key={lessonId} id={lessonId} user={user} notify={setNotice} refresh={refresh} back={()=>navigate('trail')}/>}
 {view==='teacher'&&user.role==='teacher'&&course&&<Teacher course={course} refresh={refresh} notify={setNotice} openLesson={openLesson}/>}
 {view==='history'&&<HistoryView score={user.score}/>}
 {view==='settings'&&<SettingsView user={user} refresh={refresh} notify={setNotice}/>}
 </main><footer>PythonBlock · Aprender é construir, um passo de cada vez.<span>Aprendizado de Python</span></footer></div>{notice&&<div className="toast" role="status">{notice}</div>}</div>
}
function Login({configured,onLogin}:{configured:boolean;onLogin:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[teacher,setTeacher]=useState(false);
 return <main className="login-page"><div className="login-story"><div className="brand"><span className="brand-symbol">⌘</span><span>PythonBlock<small>APRENDA PYTHON NA PRÁTICA</small></span></div><p className="eyebrow">UM NOVO JEITO DE DESCOBRIR</p><h1>Pequenos comandos.<br/>Grandes descobertas.</h1><p>Uma jornada em Python com atividades práticas,<br/>companhia e espaço para aprender no seu ritmo.</p><div className="login-pets" aria-hidden="true">🐍 💻</div><span className="tiny">SUA APRENDA PYTHON COMEÇA AQUI</span></div><section className="login-form card"><span className="pill">Bem-vindo à equipe 🌱</span><h2>Vamos continuar?</h2><p className="muted">Use o acesso que seu professor entregou.</p>{!configured?<div className="notice"><h3>Estamos preparando sua sala.</h3><p>A plataforma está aguardando a conexão com o banco de dados. Volte assim que seu professor compartilhar o acesso.</p></div>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await api('auth/login',{username:f.get('username'),password:f.get('password')});await onLogin()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}}><label>Usuário<input name="username" required autoComplete="username" maxLength={32} placeholder="Ex.: marina.silva"/></label><label>{teacher?'Senha do professor':'PIN de quatro dígitos'}<input name="password" type="password" required minLength={teacher?12:4} maxLength={teacher?128:4} inputMode={teacher?'text':'numeric'} pattern={teacher?undefined:'[0-9]{4}'} autoComplete="current-password" placeholder={teacher?'Sua senha':'••••'}/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary full" disabled={busy}>{busy?'Entrando…':'Entrar na minha trilha'} <ArrowRight size={17}/></button><label className="check-label"><input type="checkbox" checked={teacher} onChange={e=>setTeacher(e.target.checked)}/> Sou professor</label></form>}<p className="tiny login-help">Esqueceu seu acesso? Peça ao professor para redefini-lo.<br/>Seu trabalho fica salvo na sua conta.</p></section></main>
}
function HistoryView({score}:{score:string}){const [events,setEvents]=useState<any[]>([]),[error,setError]=useState('');useEffect(()=>{api('history').then(r=>setEvents(r.events)).catch(e=>setError(e.message))},[]);return <><p className="eyebrow">CADA PASSO CONTA</p><h1>Seu progresso</h1><div className="stat-card"><Sparkles/><strong>{xp(score)} XP</strong><span>acumulados na sua jornada</span></div><details className="card"><summary>Como os pontos funcionam</summary><p>Setup: 10 XP por passo. Oficinas do Capítulo 1: 25 XP por montagem e 50 XP por desafio digitado. Robô: 50, 75, 100, 150 e 200 XP, mais os desafios bônus. Quiz: 40 XP no primeiro acerto ou 20 após erro. Cada conquista pontua uma única vez.</p><p>Revelar uma solução desconta o valor mostrado no botão, sem saldo negativo. Nas montagens, o desconto é de até 10 XP; nos desafios digitados, até 20 XP; nas demais atividades e no robô, até 30 XP. A recompensa do desafio cai para 25%, e rever a mesma solução é grátis. XP de prática local não equivale a nota formal.</p></details><section className="card section-gap"><h2>Histórico de pontos</h2>{error&&<p role="alert">{error}</p>}{events.length?events.map((e,i)=><div className="history-item" key={i}><div><strong>{e.reason}</strong><small>{new Date(e.created_at).toLocaleString('pt-BR')}</small></div><span className={Number(e.amount)<0?'error':'success'}>{Number(e.amount)>0?'+':''}{xp(e.amount)} XP</span></div>):<p className="muted">Suas conquistas aparecerão aqui.</p>}</section></>}
function SettingsView({user,refresh,notify}:{user:User;refresh:()=>Promise<void>;notify:(s:string)=>void}){const [busy,setBusy]=useState(false);return <><p className="eyebrow">DO SEU JEITO</p><h1>Minha conta</h1><div className="two-grid"><section className="card"><h2>Seu espaço de aprendizagem</h2><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await api('profile',{avatar:f.get('avatar'),reduceMotion:f.has('motion')});await refresh();notify('Preferências salvas.')}catch(e){notify((e as Error).message)}finally{setBusy(false)}}}><label>Seu avatar<select name="avatar" defaultValue={user.avatar}>{['🐶','🤖','🐱','🌱','🚀'].map(a=><option key={a}>{a}</option>)}</select></label><label className="check-label"><input type="checkbox" name="motion" defaultChecked={user.reduce_motion}/> Reduzir movimentos</label><button disabled={busy} className="primary">Salvar preferências</button></form></section><section className="card"><h2>{user.role==='teacher'?'Alterar senha':'Alterar PIN'}</h2><p className="muted">Depois da alteração, entre novamente. Todas as sessões atuais serão encerradas.</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await api('password',{current:f.get('current'),next:f.get('next')});location.assign('/')}catch(e){notify((e as Error).message)}finally{setBusy(false)}}}><label>Acesso atual<input name="current" type="password" autoComplete="current-password" required/></label><label>Novo {user.role==='teacher'?'acesso (12 caracteres ou mais)':'PIN (quatro números)'}<input name="next" type="password" autoComplete="new-password" required minLength={user.role==='teacher'?12:4} maxLength={user.role==='teacher'?128:4} pattern={user.role==='student'?'[0-9]{4}':undefined}/></label><button disabled={busy} className="primary">Alterar acesso</button></form></section></div></>}
