"use client";
import { useEffect, useRef, useState, type DragEvent } from 'react';
import { ArrowDown, ArrowUp, GripVertical, Lightbulb, Play, RotateCcw, Square, X } from 'lucide-react';
import type { User } from '@/lib/auth';
import { api,xp } from './api';
import { usePython } from './use-python';

type Props={data:any;user:User;notify:(message:string)=>void;refresh:()=>Promise<void>};
type Draft={mission:number;challenge:number;blocks:string[];detective:string};
type Challenge={title:string;goal:string;target:[number,number];say?:string;loop?:string;starter?:string};
type Stage={title:string;xp:number;challenges:[Challenge,Challenge]};
const stages:Stage[]=[
 {title:'Mensagens',xp:50,challenges:[
  {title:'Olá, mundo!',goal:'Faça o robô dizer “Olá, mundo!”.',target:[0,0],say:'Olá, mundo!'},
  {title:'Python em ação',goal:'Faça o robô dizer “Python em ação!”.',target:[0,0],say:'Python em ação!'},
 ]},
 {title:'Linha reta',xp:75,challenges:[
  {title:'Dois passos',goal:'Avance 2 células até a posição (3, 1).',target:[2,0]},
  {title:'Três passos',goal:'Avance 3 células até a posição (4, 1).',target:[3,0]},
 ]},
 {title:'Curvas',xp:100,challenges:[
  {title:'Primeira curva',goal:'Avance 1, vire à direita e avance 1 até (2, 2).',target:[1,1]},
  {title:'Curva da bateria',goal:'Avance 2, vire à direita e avance 2 até a bateria em (3, 3).',target:[2,2]},
 ]},
 {title:'Repetições',xp:150,challenges:[
  {title:'Repetir avanço',goal:'Use um for para avançar 2 células até (3, 1).',target:[2,0],loop:'for i in range(2):\n    await robo.forward()'},
  {title:'Desenhar um quadrado',goal:'Use um for para percorrer um quadrado de lado 1 e voltar ao início.',target:[0,0],loop:'for i in range(4):\n    await robo.forward()\n    await robo.right()'},
 ]},
 {title:'Depuração',xp:200,challenges:[
  {title:'Dois erros escondidos',goal:'Corrija os dois-pontos e a indentação para falar e avançar 2 vezes.',target:[2,0],starter:'await robo.say("Olá, mundo!")\nfor i in range(2)\nawait robo.forward()'},
  {title:'Bloco fora do lugar',goal:'Corrija a indentação para o robô avançar 3 vezes.',target:[3,0],starter:'for i in range(3):\nawait robo.forward()'},
 ]},
];
const labels:Record<string,string>={say:'💬 Falar',forward:'↑ Avançar',right:'↱ Virar à direita',left:'↰ Virar à esquerda',loop:'⟳ Repetir'};
const baseCodes:Record<string,string>={forward:'await robo.forward()',right:'await robo.right()',left:'await robo.left()'};
const colors:Record<string,string>={say:'purple',forward:'blue',right:'amber',left:'amber',loop:'green'};
const rewardKey=(mission:number,challenge:number)=>challenge===1?'robot:'+mission:`robot:${mission}:${challenge}`;
function starterFor(mission:number,challenge:number){return stages[mission-1].challenges[challenge-1].starter||''}
function initialDraft(data:any):Draft{const fallback={mission:1,challenge:1,blocks:[],detective:starterFor(5,1)};try{const value=JSON.parse(data.draft?.code||'null');return value&&Array.isArray(value.blocks)&&value.mission>=1&&value.mission<=5?{...fallback,...value,challenge:value.challenge===2?2:1}:fallback}catch{return fallback}}
function useRobotDraft(value:Draft,initial:any){const version=useRef(initial?.version||0),last=useRef(initial?.code||''),[status,setStatus]=useState('Salvo na conta');useEffect(()=>{const code=JSON.stringify(value);if(code===last.current)return;setStatus('Alterações ainda não salvas');const timer=setTimeout(async()=>{setStatus('Salvando…');try{const result=await api('lessons/robo/draft',{code,stdin:'',version:version.current});version.current=result.version;last.current=code;setStatus('Salvo na conta')}catch(e){setStatus((e as any).status===409?'Conflito entre abas. Recarregue a aula.':'Sem conexão: sequência ainda não salva.')}},850);return()=>clearTimeout(timer)},[value]);return status}
export default function RobotLab({data,user,notify,refresh}:Props){
 const initial=initialDraft(data),[mission,setMission]=useState(initial.mission),[challenge,setChallenge]=useState(initial.challenge),[blocks,setBlocks]=useState<string[]>(initial.blocks),[detective,setDetective]=useState(initial.detective),[rewards,setRewards]=useState<string[]>(data.rewards),[hints,setHints]=useState<string[]>(data.hints),[solution,setSolution]=useState(''),[win,setWin]=useState(''),[busy,setBusy]=useState(false),[dropAt,setDropAt]=useState<number|null>(null);
 const dragging=useRef(''),python=usePython(),stage=stages[mission-1],current=stage.challenges[challenge-1],draft={mission,challenge,blocks,detective},saveStatus=useRobotDraft(draft,data.draft),blockCodes={...baseCodes,say:`await robo.say(${JSON.stringify(current.say||'Olá, mundo!')})`,loop:current.loop||'for i in range(4):\n    await robo.forward()\n    await robo.right()'},code=mission===5?detective:blocks.map(block=>blockCodes[block as keyof typeof blockCodes]).join('\n');
 function resetExercise(message='Exercício reiniciado. Monte uma nova solução.'){setBlocks([]);setDetective(starterFor(mission,challenge));setSolution('');setWin('');setDropAt(null);python.clear();notify(message)}
 function chooseStage(next:number){setMission(next);setChallenge(1);setBlocks([]);setDetective(starterFor(next,1));setSolution('');setWin('');python.clear()}
 function chooseChallenge(next:number){setChallenge(next);setBlocks([]);setDetective(starterFor(mission,next));setSolution('');setWin('');python.clear()}
 function place(payload:string,index:number){if(python.running||busy||mission===5)return;const separator=payload.indexOf(':'),source=payload.slice(0,separator),value=payload.slice(separator+1);if(source==='new'&&blockCodes[value as keyof typeof blockCodes])setBlocks(list=>{const next=[...list];next.splice(index,0,value);return next.slice(0,40)});if(source==='placed')setBlocks(list=>{const from=Number(value);if(!Number.isInteger(from)||!list[from])return list;const next=[...list],[item]=next.splice(from,1);next.splice(from<index?index-1:index,0,item);return next});setDropAt(null);setWin('')}
 function drop(event:DragEvent,index:number){event.preventDefault();place(event.dataTransfer.getData('text/plain')||dragging.current,index);dragging.current=''}
 async function execute(){setWin('');try{const result=await python.run(code,'',true);setBusy(true);const response=await api('lessons/robo/practice',{mission,challenge,...result});if(response.correct){const key=rewardKey(mission,challenge);setRewards(value=>value.includes(key)?value:[...value,key]);setWin(response.gain?'Desafio concluído! +'+xp(response.gain)+' XP':'Você conseguiu novamente! Este desafio já pontuou.');await refresh()}else notify('O código rodou. Confira o objetivo e ajuste sua sequência.')}catch(error){notify((error as Error).message.includes('Python')?'Confira a saída do Python.':(error as Error).message.slice(-150))}finally{setBusy(false)}}
 const completed=rewards.filter(key=>key===`robot:${mission}`||key.startsWith(`robot:${mission}:`)).length;
 return <section className="robot-lab">
  <div className="robot-visual-guide" aria-label="Etapas da atividade"><span>🧩 Escolha comandos</span><b>→</b><span>🐍 Veja o Python</span><b>→</b><span>🤖 Observe o robô</span></div>
  <div className="mission-tabs">{stages.map((item,index)=><button key={item.title} disabled={python.running||busy} aria-pressed={mission===index+1} className={mission===index+1?'active':''} onClick={()=>chooseStage(index+1)}><strong>{rewards.includes('robot:'+(index+1))&&rewards.includes(`robot:${index+1}:2`)?'✓ ':''}{index+1}. {item.title}</strong><small>2 desafios · {item.xp} XP + bônus</small></button>)}</div>
  <div className="challenge-picker" aria-label="Desafios desta etapa"><div><span className="eyebrow">ETAPA {mission} · {completed}/2 CONCLUÍDOS</span><h2>{stage.title}</h2></div>{stage.challenges.map((item,index)=>{const key=rewardKey(mission,index+1);return <button key={item.title} aria-pressed={challenge===index+1} className={challenge===index+1?'active':''} disabled={python.running||busy} onClick={()=>chooseChallenge(index+1)}><span>{rewards.includes(key)?'✓':'◇'}</span><span><small>DESAFIO {index+1}</small><strong>{item.title}</strong></span></button>})}</div>
  <div className="card"><div className="row between wrap"><div><p className="eyebrow">DESAFIO {challenge} DE 2</p><h2>{current.title}</h2></div><div className="row wrap"><span className="save-state" role="status">{saveStatus}</span><button className="small reset-exercise" disabled={python.running||busy} onClick={()=>resetExercise()}><RotateCcw size={15}/> Reiniciar exercício</button></div></div><p>{current.goal}</p>
   <div className="robot-workspace"><div><h3>① Arraste seus blocos</h3><p className="tiny">Arraste para a sequência ou clique para acrescentar. Você pode repetir comandos.</p><div className="palette">{Object.entries(labels).map(([key,label])=><button key={key} className={'robot-palette-block '+colors[key]} draggable={mission!==5&&!python.running&&!busy} disabled={mission===5||python.running||busy||blocks.length>=40} onPointerDown={()=>{dragging.current='new:'+key}} onMouseDown={()=>{dragging.current='new:'+key}} onDragStart={event=>{dragging.current='new:'+key;event.dataTransfer.setData('text/plain','new:'+key);event.dataTransfer.effectAllowed='copy'}} onClick={()=>place('new:'+key,blocks.length)}>{label}</button>)}</div>
    <h3 className="section-gap">② Monte sua sequência</h3><ol className="pipeline" aria-label="Sequência de comandos">{Array.from({length:blocks.length+1},(_,index)=>{const block=blocks[index];return <li key={block?index+'-'+block:'end'}><div className={'robot-drop-zone '+(dropAt===index?'over':'')} data-robot-drop={index} onDragOver={event=>{event.preventDefault();setDropAt(index)}} onDragLeave={()=>setDropAt(null)} onPointerUp={()=>{if(dragging.current){place(dragging.current,index);dragging.current=''}}} onDrop={event=>drop(event,index)}>{index===blocks.length?(blocks.length?'Solte aqui para acrescentar':'Solte o primeiro comando aqui'):'Solte aqui para inserir'}</div>{block&&<div className={'block robot-sequence-block '+colors[block]} draggable={!python.running&&!busy} onPointerDown={()=>{dragging.current='placed:'+index}} onMouseDown={()=>{dragging.current='placed:'+index}} onDragStart={event=>{dragging.current='placed:'+index;event.dataTransfer.setData('text/plain','placed:'+index);event.dataTransfer.effectAllowed='move'}}><GripVertical size={15} aria-hidden="true"/><span><small>{index+1}. comando</small>{labels[block]}</span><button className="icon-button" aria-label={'Mover bloco '+(index+1)+' para cima'} disabled={index===0||python.running} onClick={()=>setBlocks(list=>{const next=[...list];[next[index-1],next[index]]=[next[index],next[index-1]];return next})}><ArrowUp size={13}/></button><button className="icon-button" aria-label={'Mover bloco '+(index+1)+' para baixo'} disabled={index===blocks.length-1||python.running} onClick={()=>setBlocks(list=>{const next=[...list];[next[index+1],next[index]]=[next[index],next[index+1]];return next})}><ArrowDown size={13}/></button><button className="icon-button" aria-label={'Remover bloco '+(index+1)} disabled={python.running} onClick={()=>setBlocks(list=>list.filter((_,itemIndex)=>itemIndex!==index))}><X size={13}/></button></div>}</li>})}</ol>{mission===5&&<p className="notice">Nesta etapa, encontre os erros e corrija o Python diretamente no editor ao lado.</p>}</div>
    <div><label className="editor-label">③ Código Python<textarea className="code-editor" value={code} maxLength={20000} onChange={event=>setDetective(event.target.value)} spellCheck={false} readOnly={mission!==5||python.running}/></label><div className="row wrap"><button className="primary" disabled={python.running||busy||!code.trim()} onClick={execute}><Play size={15}/>{python.running?'Executando…':'Executar Python'}</button>{python.running&&<button onClick={python.stop}><Square size={15}/> Parar</button>}</div><p className="tiny" role="status">{python.status}</p></div></div>
   <div className="robot-result"><div><div className="board" role="img" aria-label={`Tabuleiro cinco por cinco. Robô na coluna ${python.robot.x+1}, linha ${python.robot.y+1}.`}>{Array.from({length:25},(_,index)=>{const x=index%5,y=Math.floor(index/5),here=python.robot.x===x&&python.robot.y===y,target=current.target[0]===x&&current.target[1]===y;return <div key={index} className={'cell '+(target?'target ':'')+(python.robot.visited.some(position=>position[0]===x&&position[1]===y)?'visited':'')}><span>{here?'🤖':target&&mission===3&&challenge===2?'🔋':target?'◎':''}</span>{here&&<b>{['→','↓','←','↑'][python.robot.d]}</b>}<small>{x+1},{y+1}</small></div>})}</div><p className="board-caption">Tabuleiro 5 × 5 · cada quadrado representa uma posição</p></div><div><div className="robot-speech" role="status">🤖 {python.robot.words.at(-1)||'Uma instrução de cada vez. Estou pronto.'}</div><label>Saída do Python<pre className="code-output" aria-live="polite">{python.output||'Seu resultado aparece aqui.'}</pre></label></div></div>
   {win&&<div className="victory" role="status">🌱 {win}</div>}<button className="warning" disabled={python.running||busy} onClick={async()=>{setBusy(true);try{const response=await api('lessons/robo/solution',{mission,challenge});setSolution(response.solution);const key=rewardKey(mission,challenge);setHints(value=>value.includes(key)?value:[...value,key]);await refresh();notify(response.gain<0?'Solução revelada! '+xp(response.gain)+' XP':'Solução disponível.')}catch(error){notify((error as Error).message)}finally{setBusy(false)}}}><Lightbulb size={15}/>{hints.includes(rewardKey(mission,challenge))||user.role==='teacher'?'Rever solução':'Revelar solução · até −30 XP'}</button><p className="tiny">Ao revelar, a recompensa deste desafio passa a 25%. A mesma solução desconta apenas uma vez. XP de prática local não é nota formal.</p>{solution&&<div className="solution-box"><div className="row between"><h3>Um caminho possível</h3><button className="small" onClick={()=>setSolution('')}>Fechar</button></div><pre>{solution}</pre></div>}</div>
 </section>
}
