"use client";
import { useEffect, useState } from 'react';
import { Users, BookOpen, FileCheck, Plus, Download } from 'lucide-react';
import {api,xp} from './api';
export default function Teacher({course,refresh,notify,openLesson}:{course:any;refresh:()=>Promise<void>;notify:(s:string)=>void;openLesson:(s:string)=>void}){
 const [tab,setTab]=useState('lessons'),[students,setStudents]=useState<any[]>([]),[submissions,setSubmissions]=useState<any[]>([]),[busy,setBusy]=useState(false),[credential,setCredential]=useState<any>(null),[error,setError]=useState('');
 async function load(){try{const [a,b]=await Promise.all([api('teacher/students'),api('teacher/submissions')]);setStudents(a.students);setSubmissions(b.submissions)}catch(e){setError((e as Error).message)}}useEffect(()=>{void load()},[]);
 async function action(fn:()=>Promise<void>){setBusy(true);try{await fn()}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 function exportCSV(){const cell=(v:any)=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const csv='\uFEFF'+[['Nome','Usuário','XP','Aulas concluídas','Ativo'],...students.map(s=>[s.name,s.username,s.score,s.completed,s.active?'Sim':'Não'])].map(r=>r.map(cell).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='progresso-pythonblock.csv';a.click();URL.revokeObjectURL(url)}
 return <><div className="page-heading"><div><p className="eyebrow">ACOMPANHE CADA DESCOBERTA</p><h1>Painel do professor</h1><p className="muted">Organize o ritmo da turma e dê apoio onde ele faz diferença.</p></div><span className="pill">{course.className}</span></div><div className="stats-grid"><div className="stat-card"><Users/><strong>{students.filter(s=>s.active).length}</strong><span>alunos ativos</span></div><div className="stat-card"><BookOpen/><strong>{course.lessons.filter((l:any)=>l.published&&l.released).length}</strong><span>aulas liberadas</span></div><div className="stat-card"><FileCheck/><strong>{submissions.filter(s=>s.status==='pending').length}</strong><span>entregas para revisar</span></div></div><div className="tabs" aria-label="Áreas do professor">{[['lessons','Aulas e liberações'],['students','Alunos'],['submissions','Entregas']].map(([id,label])=><button aria-pressed={tab===id} className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div>{error&&<p className="error" role="alert">{error}</p>}
 {tab==='lessons'&&<section className="card"><h2>O próximo passo é você quem libera.</h2><p className="muted">A alteração passa a valer sem republicar o site. As aulas em preparação precisam receber conteúdo antes de serem liberadas.</p>{course.chapters.map((ch:any)=><div className="release-group" key={ch.id}><h3>{String(ch.id).padStart(2,'0')} · {ch.title}</h3>{course.lessons.filter((l:any)=>l.chapter===ch.id).map((l:any)=><div className="release-row" key={l.id}><div><strong>{l.title}</strong><small>{!l.published?'Em preparação':l.released?'Liberada para a turma':l.release_at?'Agendada: '+new Date(l.release_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Bloqueada'}</small></div>{l.published&&<div className="row"><button className="small" onClick={()=>openLesson(l.id)}>Visualizar</button><button className={'small '+(!l.released?'primary':'')} disabled={busy} onClick={()=>action(async()=>{await api('teacher/release',{lessonId:l.id,mode:l.released?'block':'release'});await refresh();notify(l.released?'Aula bloqueada. Histórico preservado.':'Aula liberada para a turma.')} )}>{l.released?'Bloquear':'Liberar'}</button><details><summary className="small">Agendar</summary><form className="schedule-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action(async()=>{await api('teacher/release',{lessonId:l.id,mode:'schedule',date:f.get('date')+':00-03:00'});await refresh();notify('Agendamento salvo.')})}}><label>Brasília (UTC−3)<input type="datetime-local" name="date" required/></label><button disabled={busy}>Salvar</button></form></details></div>}</div>)}</div>)}</section>}
 {tab==='students'&&<><section className="card"><div className="row between"><h2>Criar acesso de aluno</h2><span className="pill">PIN gerado automaticamente</span></div><form className="inline-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);void action(async()=>{const result=await api('teacher/students',{name:f.get('name'),username:f.get('username')});setCredential(result);form.reset();await load()})}}><label>Nome<input name="name" required minLength={2} maxLength={80} placeholder="Nome do aluno"/></label><label>Usuário<input name="username" required pattern="[a-zA-Z0-9_.\-]{3,30}" placeholder="Ex.: marina.silva"/></label><button className="primary" disabled={busy}><Plus size={17}/> Criar acesso</button></form>{credential&&<div className="credential" role="status"><strong>Entregue este acesso somente ao aluno.</strong><p>Usuário: <b>{credential.username}</b> · PIN: <b>{credential.pin}</b></p><button className="small" onClick={()=>setCredential(null)}>Já anotei, ocultar</button></div>}</section><section className="card section-gap"><div className="row between"><h2>Alunos da turma</h2><button onClick={exportCSV} disabled={!students.length}><Download size={16}/> Exportar progresso</button></div>{!students.length?<p className="empty">A turma começa com o primeiro acesso. Cadastre um aluno acima.</p>:<div className="table-wrap"><table><thead><tr><th>Aluno</th><th>Progresso</th><th>XP</th><th>Acesso</th><th>Ações</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td><strong>{s.avatar} {s.name}</strong><small>{s.username}</small></td><td>{s.completed} aulas</td><td>{xp(s.score)}</td><td>{s.active?'Ativo':'Desativado'}</td><td><div className="row"><button className="small" disabled={busy} onClick={()=>action(async()=>{const data=await api('teacher/student-action',{id:s.id,action:'reset'});setCredential({username:s.username,pin:data.pin});notify('PIN redefinido. As sessões anteriores foram encerradas.')})}>Redefinir PIN</button><button className="small" disabled={busy} onClick={()=>action(async()=>{await api('teacher/student-action',{id:s.id,action:s.active?'deactivate':'activate'});await load()})}>{s.active?'Desativar':'Ativar'}</button></div></td></tr>)}</tbody></table></div>}</section></>}
 {tab==='submissions'&&<section><p className="notice">As saídas abaixo foram produzidas no navegador do aluno. Revise o código e registre seu feedback; execução local não é uma nota automática.</p>{!submissions.length?<div className="card empty">As entregas da turma aparecerão aqui.</div>:submissions.map(s=><article className="card section-gap" key={s.id}><div className="row between"><h3>{s.name} · {s.title}</h3><span className="pill">{s.status==='reviewed'?'Revisada':'Aguardando revisão'}</span></div><p className="tiny">{new Date(s.created_at).toLocaleString('pt-BR')}</p><details><summary>Ver código e resultado</summary><pre className="code-output">{s.code}</pre><h4>Entradas</h4><pre className="code-output">{s.stdin||'Sem entradas'}</pre><h4>Saída informada</h4><pre className="code-output">{s.output||'Sem saída'}</pre></details><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action(async()=>{await api('teacher/feedback',{id:s.id,feedback:f.get('feedback')});await load();notify('Feedback enviado ao aluno.')})}}><label>Seu feedback<textarea name="feedback" defaultValue={s.feedback} required maxLength={3000} rows={3} placeholder="O que já está funcionando? Qual é o próximo passo?"/></label><button disabled={busy} className="primary">Salvar feedback</button></form></article>)}</section>}
 </>
}
